# Generated by Django 3.1.3 on 2020-12-14 11:33

import car_rental.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=6, validators=[car_rental.models.PostalCodeValidator()])),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=8)),
                ('vin', models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(17)])),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=45)),
                ('production_year', models.IntegerField(max_length=4, validators=[django.core.validators.MaxValueValidator(2020)])),
                ('color', models.CharField(max_length=15)),
                ('car_status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('serviced', 'serviced')], default='available', max_length=15)),
                ('daily_cost_of_rent', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=45)),
                ('phone_number', models.CharField(max_length=9)),
                ('address_id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='car_rental.address')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=9)),
                ('title', models.CharField(choices=[('manager', 'Manager'), ('consultant', 'Consultant'), ('service technician', 'service technician')], default='manager', max_length=20)),
                ('address_id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='car_rental.address')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost_of_rent', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('car_id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='car_rental.car')),
                ('client_id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='car_rental.client')),
                ('employee_id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='car_rental.employee')),
            ],
        ),
    ]
